name: Test
on:
  push:
  pull_request:
jobs:
  full:
    name: Node.js 16 Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn
      - name: Install pnpm
        run: yarn global add pnpm
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
        env:
          FORCE_COLOR: 2
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 14
          - 12
          - 10
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install pnpm
        run: npm add -g pnpm
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines
      - name: Run unit tests
        run: npx jest
        env:
          FORCE_COLOR: 2
  short8:
    runs-on: ubuntu-latest
    name: Node.js 8 Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js 8
        uses: actions/setup-node@v2
        with:
          node-version: 8
          cache: yarn
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Run unit tests
        run: npx jest
        env:
          FORCE_COLOR: 2
